python -m torch.distributed.launch \
    --nproc_per_node=8 \
    --use_env main.py \
    --model deit_base_patch16_224 \
    --epochs 600 \
    --batch-size 128 \
    --data-path $1 \
    --output_dir ./base_dst_uns_0507 \
    --dist_url tcp://127.0.0.1:23305 \
    --sparse_init fixed_ERK \
    --density 0.6 \
    --update_frequency 7000 \
    --growth gradient \
    --death magnitude \
    --redistribution none \
    --num_workers $2